#!/bin/bash

docker rm -f docker-ubuntu

docker build -t docker-ubuntu .

docker create   --name docker-ubuntu \
                -p 23389:3389 \
                -t \
                -v /${PWD}:/root \
                docker-ubuntu


echo "Your image and container have been built. It will now be started"
docker start docker-ubuntu
docker exec -it docker-ubuntu bash
